DROP TABLE CREDIT_CARD_BILL IF EXISTS;
CREATE TABLE CREDIT_CARD_BILL (
   CardNumber VARCHAR(20) NOT NULL PRIMARY KEY,
   BillDueDate VARCHAR(10),
   DueAmount DOUBLE,
   CardType VARCHAR(20)	
);